kind: Pod
apiVersion: v1
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  serviceAccountName: webapp-sa
  containers:
  - image: tanquetav/quarkusvault
    imagePullPolicy: Always
    name: webapp
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-database"
