apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32200
  type: NodePort
  selector:
    app: webapp
